version: '3.8'

services:
  # Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: resumegen-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - resumegen-network

  # Backend API
  api:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: resumegen-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ResumeGeneratorDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
      - JWT__SecretKey=your-super-secret-jwt-key-here-make-it-long-and-secure
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - Azure__ClientId=${AZURE_CLIENT_ID}
      - Azure__ClientSecret=${AZURE_CLIENT_SECRET}
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - resumegen-network
    volumes:
      - ./src/backend:/app
    command: ["dotnet", "watch", "run", "--project", "ResumeGenerator.API"]

  # Frontend
  web:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: resumegen-web
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
      - VITE_SIGNALR_HUB_URL=http://localhost:5000/resumeHub
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - resumegen-network
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # Redis for SignalR backplane (optional for scaling)
  redis:
    image: redis:7-alpine
    container_name: resumegen-redis
    ports:
      - "6379:6379"
    networks:
      - resumegen-network

volumes:
  db_data:

networks:
  resumegen-network:
    driver: bridge
